### ISSUE TITLE
Clarify values expected by AppleShove.notify()

### ISSUE THREAD

**Issue by ismith** [tboyko/apple_shove#4]
Can you clarify the values needed by AppleShove.notify()?  I've got the PushMagic string for a device, that's pretty straightforward, but Apple's MDM documentation says that what comes back on enrollment in the Token property is Data.  So, looking at the example in the readme, should the value of the :device_token key be ... the string inside the <Data> tags?  Or the value I get when I B64-decode that?

**Comment by tboyko** [comment]
`:device_token` expects a string. You'll need to convert the token you receive during MDM enrollment. I generally do something like this to decode the data Apple sends me into hex:

```
hex_token_for_apple_shove = apple_data_token.unpack( 'H*' ).first
```

**Comment by ismith** [comment]
That worked perfectly, thanks.  (As a note for anyone coming across this issue later, the apple_data_token referenced above is not B64 encoded - so the string inside the <Data> block, base64 decoded and then unpack('H*')'ed.)

**Comment by tboyko** [comment]
Thanks for the extra note, Ian. Glad it's working for you.
